import { BadRequestException } from '@nestjs/common'
import { Test, TestingModule } from '@nestjs/testing'
import { ExchangeService } from './exchange.service'

describe('ExchangeService', () => {
  let service: ExchangeService

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [ExchangeService],
    }).compile()

    service = module.get<ExchangeService>(ExchangeService)
  })

  it('should be defined', () => {
    expect(service).toBeDefined()
  })

  describe('ConvertAmount()', () => {
    it('should be throw if called with invalid params', async () => {
      await expect(service.convertAmount({ from: '', to: '', amount: 0 })).rejects.toThrow(new BadRequestException())
    })

    it('should be not throw if called with valid params', async () => {
      await expect(service.convertAmount({ from: 'USD', to: 'BRL', amount: 1 })).resolves.not.toThrow()
    })
  })
})
